version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
    volumes:
      - ./.env:/app/.env  # Mount the .env file to the /app/.env path inside the container
    env_file:
      - .env  # Load environment variables from the .env file
    restart: unless-stopped
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data:
